-- ============================================================================
-- Create PATRON Oracle User and Link to ROLE_PATRON
-- Run as SYS or PROJET_ADMIN
-- ============================================================================

-- Step 1: Create Oracle user PATRON
CREATE USER PATRON IDENTIFIED BY "PatronPass123";

-- Step 2: Grant basic connection privilege
GRANT CREATE SESSION TO PATRON;

-- Step 3: Create ROLE_PATRON if it doesn't exist
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM DBA_ROLES WHERE ROLE = 'ROLE_PATRON';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE ROLE ROLE_PATRON';
        DBMS_OUTPUT.PUT_LINE('✓ ROLE_PATRON created');
    ELSE
        DBMS_OUTPUT.PUT_LINE('✓ ROLE_PATRON already exists');
    END IF;
END;
/

-- Step 4: Grant permissions to ROLE_PATRON
GRANT SELECT ON PROJET_ADMIN.MATERIALS TO ROLE_PATRON;
GRANT SELECT ON PROJET_ADMIN.AUTHORS TO ROLE_PATRON;
GRANT SELECT ON PROJET_ADMIN.PUBLISHERS TO ROLE_PATRON;
GRANT SELECT ON PROJET_ADMIN.GENRES TO ROLE_PATRON;
GRANT SELECT ON PROJET_ADMIN.MATERIAL_AUTHORS TO ROLE_PATRON;
GRANT SELECT ON PROJET_ADMIN.MATERIAL_GENRES TO ROLE_PATRON;
GRANT SELECT ON PROJET_ADMIN.COPIES TO ROLE_PATRON;
GRANT SELECT ON PROJET_ADMIN.BRANCHES TO ROLE_PATRON;
GRANT SELECT ON PROJET_ADMIN.PATRONS TO ROLE_PATRON;
GRANT SELECT ON PROJET_ADMIN.LOANS TO ROLE_PATRON;
GRANT SELECT ON PROJET_ADMIN.RESERVATIONS TO ROLE_PATRON;
GRANT SELECT ON PROJET_ADMIN.FINES TO ROLE_PATRON;

-- Grant execute on procedures
GRANT EXECUTE ON PROJET_ADMIN.SP_PLACE_RESERVATION TO ROLE_PATRON;
GRANT EXECUTE ON PROJET_ADMIN.SP_CANCEL_RESERVATION TO ROLE_PATRON;
GRANT EXECUTE ON PROJET_ADMIN.FN_CHECK_MATERIAL_AVAILABILITY TO ROLE_PATRON;
GRANT EXECUTE ON PROJET_ADMIN.FN_GET_PATRON_STATISTICS TO ROLE_PATRON;
GRANT EXECUTE ON PROJET_ADMIN.SP_AUTHENTICATE_USER TO ROLE_PATRON;
GRANT EXECUTE ON PROJET_ADMIN.SP_LOGOUT_USER TO ROLE_PATRON;

-- Step 5: Assign ROLE_PATRON to PATRON user
GRANT ROLE_PATRON TO PATRON;

-- Step 6: Verify
SET SERVEROUTPUT ON;
DECLARE
    v_count NUMBER;
BEGIN
    DBMS_OUTPUT.PUT_LINE('========================================');
    DBMS_OUTPUT.PUT_LINE('VERIFICATION');
    DBMS_OUTPUT.PUT_LINE('========================================');
    
    -- Check user exists
    SELECT COUNT(*) INTO v_count FROM DBA_USERS WHERE USERNAME = 'PATRON';
    DBMS_OUTPUT.PUT_LINE('User PATRON exists: ' || CASE WHEN v_count > 0 THEN 'YES ✓' ELSE 'NO ✗' END);
    
    -- Check role granted
    SELECT COUNT(*) INTO v_count FROM DBA_ROLE_PRIVS WHERE GRANTEE = 'PATRON' AND GRANTED_ROLE = 'ROLE_PATRON';
    DBMS_OUTPUT.PUT_LINE('ROLE_PATRON granted: ' || CASE WHEN v_count > 0 THEN 'YES ✓' ELSE 'NO ✗' END);
    
    DBMS_OUTPUT.PUT_LINE('========================================');
    DBMS_OUTPUT.PUT_LINE('User: PATRON');
    DBMS_OUTPUT.PUT_LINE('Password: PatronPass123');
    DBMS_OUTPUT.PUT_LINE('========================================');
END;
/

COMMIT;

PROMPT Setup complete! Test with:
PROMPT CONNECT PATRON/PatronPass123
PROMPT SELECT COUNT(*) FROM MATERIALS;
