-- ============================================================================
-- FIX: Grant Patron Permissions for Material Browsing
-- This script grants necessary SELECT permissions to ROLE_PATRON
-- ============================================================================

-- Grant SELECT on basic tables needed for browsing
GRANT SELECT ON PROJET_ADMIN.MATERIALS TO ROLE_PATRON;
GRANT SELECT ON PROJET_ADMIN.AUTHORS TO ROLE_PATRON;
GRANT SELECT ON PROJET_ADMIN.PUBLISHERS TO ROLE_PATRON;
GRANT SELECT ON PROJET_ADMIN.GENRES TO ROLE_PATRON;
GRANT SELECT ON PROJET_ADMIN.MATERIAL_AUTHORS TO ROLE_PATRON;
GRANT SELECT ON PROJET_ADMIN.MATERIAL_GENRES TO ROLE_PATRON;
GRANT SELECT ON PROJET_ADMIN.COPIES TO ROLE_PATRON;
GRANT SELECT ON PROJET_ADMIN.BRANCHES TO ROLE_PATRON;

-- Grant SELECT on tables for patron's own data
GRANT SELECT ON PROJET_ADMIN.PATRONS TO ROLE_PATRON;
GRANT SELECT ON PROJET_ADMIN.LOANS TO ROLE_PATRON;
GRANT SELECT ON PROJET_ADMIN.RESERVATIONS TO ROLE_PATRON;
GRANT SELECT ON PROJET_ADMIN.FINES TO ROLE_PATRON;

-- Grant access to views
GRANT SELECT ON PROJET_ADMIN.VIEW_POPULAR_BOOKS TO ROLE_PATRON;
GRANT SELECT ON PROJET_ADMIN.VIEW_MATERIAL_DISTRIBUTION TO ROLE_PATRON;

-- Grant EXECUTE on patron-specific procedures
GRANT EXECUTE ON PROJET_ADMIN.SP_PLACE_RESERVATION TO ROLE_PATRON;
GRANT EXECUTE ON PROJET_ADMIN.SP_CANCEL_RESERVATION TO ROLE_PATRON;
GRANT EXECUTE ON PROJET_ADMIN.FN_CHECK_MATERIAL_AVAILABILITY TO ROLE_PATRON;
GRANT EXECUTE ON PROJET_ADMIN.FN_GET_PATRON_STATISTICS TO ROLE_PATRON;

COMMIT;
